repos:
  # Use pre-commit repo, v3.2.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
        stages: [commit, push]
      # Simply check whether files parse as valid python.
      - id: check-ast
        stages: [commit]
      # Remove trailing whitespaces
      - id: trailing-whitespace
        stages: [commit]
      # Add newlines to the end of files
      - id: end-of-file-fixer
        stages: [commit]

    # Use locally installed hooks
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]

      - id: ruff (isort)
        name: ruff-isort
        entry: poetry run ruff --select I --select F401 --fix
        language: system
        types: [python]
        stages: [commit]

      - id: ruff
        name: ruff check
        entry: poetry run ruff check
        language: system
        types: [python]
        stages: [commit]

      - id: mypy
        name: mypy check
        entry: poetry run mypy vkbottle
        language: system
        pass_filenames: false
        stages: [commit]


      - id: pytest
        name: pytest
        entry: poetry run pytest vkbottle
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]
