version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - poetry config virtualenvs.create false
      - poetry install --only docs
      - poetry env info

mkdocs:
  configuration: mkdocs.yml
