name: CI

on:
  push:
    branches: [ master, v3.0 ]
  pull_request:
    branches: [ master, v3.0 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Lint code
        run: |
          poetry run flake8
          poetry run mypy vkbottle

      - name: Set enviromental variables to run tests
          uses: allenevans/set-env@v1.0.0
          with:
            TOKEN: ${{ secrets.test_token }}

      - name: Run tests
        run: |
          poetry run pytest